### ISSUE TITLE
why require `query` twice? any trick here?

### ISSUE THREAD

**Issue by newlife** [onechain/fabric-explorer#17]
https://github.com/onechain/fabric-explorer/blob/0877bea3fecf1ba8320a4f4ef713c2e8b23c7a46/main.js#L30

https://github.com/onechain/fabric-explorer/blob/0877bea3fecf1ba8320a4f4ef713c2e8b23c7a46/main.js#L18

**Comment by gcc2ge** [comment]
we have  fixed the bug,thanks.
